version: '3.8'

services:
  employee-service:
    image: employee-service
    build:
      context: ./employee-service
    ports:
      - "8083:8083"
    networks:
      - microservices-net

  department-service:
    image: department-service
    build:
      context: ./department-service
    ports:
      - "8084:8084"
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge